### PR TITLE
Fix Debates

### LINKED ISSUE #56: 500 error on Debates
_From @andreslucena on February 15, 2017 11:34_

# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong? If I go to a Debate on the PAM process it doesn't work 
* What did you expect should have happened? To work 
* What stacktrace or error message from your provider did you see? 500 error

#### :pushpin: Related issues
* #813 
* #874 

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: decidim.barcelona
* ***Browser & version***: Firefox 51.0.1
* ***Screenshot***: 
* ***Error messages***: 500 error, "Hi ha hagut un problema amb el nostre servidor. Si us plau, torna-ho a intentar més tard."
* ***URL to reproduce the error***: https://decidim.barcelona/processes/1/f/9/debates/1  

_Copied from original issue: AjuntamentdeBarcelona/decidim#971_

### PR DESCRIPTION
**Pull request by oriolgual**
#### :tophat: What? Why?

The debates engine wasn't being ran at Travis so we didn't know it was broken after updating Decidim. This PR adds the engine to the build script and fixes it.

#### :pushpin: Related Issues
- Fixes #56

### CODE REVIEW

File: config/initializers/decidim.rb [hunk 1]
```diff
@@ -7,7 +7,8 @@
   config.authorization_handlers = [CensusAuthorizationHandler]
   config.maximum_attachment_size = 150.megabytes
 
-  config.available_locales = %i(en ca es)
+  config.available_locales = %i(ca es)
```
Comment (mrcasals) [inline config/initializers/decidim.rb]: We might need to update the organization `available_locales`!

Comment (oriolgual) [inline config/initializers/decidim.rb]: You mean at production?

**Comment by oriolgual** [comment]
Build works but is reported as broken due to codecov being down.
